<html>
<head>
    <meta charset="UTF-8">
    <style type="text/css">
        html, body {
            font-family: "Segoe UI";
            color: #808080;
            font-size: 14px;
        }
    </style>
</head>
<body>
<?php
$eng = array(
    "straight hair",
    "baldgirl",
    "cortedepelo",
    "yellow",
    "girl hairstyles",
    "calva",
    "longhairdontcare",
    "purple",
    "color",
    "extremehaircut",
    "green",
    "short hair",
    "fashion style",
    "extreme",
    "capellicorti",
    "pelocorto",
    "tattoo",
    "rapado",
    "cute hair",
    "dye",
    "red",
    "hairart",
    "bowl",
    "colorful",
    "hairdesign",
    "bob",
    "white",
    "curly hair",
    "haircolor",
    "shorthairdontcare",
    "art",
    "blue",
    "rasatura",
    "longhair",
    "bald",
    "white hair",
    "women",
    "bangs",
    "capelli",
    "sideshave",
    "tail",
    "mohawk",
    "rasiert",
    "bobhaircut",
    "hairdye",
    "rasata",
    "shortcut",
    "pink",
    "trendy",
    "fashionista",
    "hairdo",
    "pastelhair",
    "pelo",
    "wavy hair",
    "headshave",
    "rapada",
    "undershave",
    "hairfashion",
    "bobcut",
    "shaved",
    "buzzed",
    "trend",
    "bowlcut",
    "sidecut",
    "shorthair",
    "braided",
    "braids",
    "fantastic",
    "blonde hair",
    "undercut",
    "braided hair",
    "dyed",
    "blonde",
    "straight",
    "beautiful girl",
    "amazing",
    "Hair Styles",
    "haircut",
    "kids",
    "hair color",
    "hair style",
    "style",
    "cool",
    "Beautiful",
    "long hair",
    "evening",
    "braid",
    "hairstyles",
    "beauty",
    "short",
    "girl",
    "Fashion",
    "hairstyle",
    "curls",
    "exlusive",
    "unstandart",
    "medium",
    "netting",
    "everyday",
    "bunch",
    "wedding",
    "long"
);
$rus = array(
    "прямые волосы",
    "лысая дувушка",
    "cortedepelo",
    "желтый",
    "прически для девочек",
    "сalva",
    "longhairdontcare",
    "пурпурный",
    "цвет",
    "extremehaircut",
    "зеленый",
    "короткие волосы",
    "модный стиль",
    "экстремальный",
    "capellicorti",
    "pelocorto",
    "тату",
    "rapado",
    "милые",
    "окрашенные",
    "красный",
    "арт",
    "bowl",
    "красочный",
    "hairdesign",
    "боб",
    "белый",
    "вьющиеся волосы",
    "цвет волос",
    "shorthairdontcare",
    "арт",
    "синий",
    "rasatura",
    "длинные волосы",
    "bald",
    "белые волосы",
    "женские",
    "челка",
    "Капелли",
    "sideshave",
    "хвост",
    "mohawk",
    "rasiert",
    "стрижка каре",
    "окрашевание",
    "rasata",
    "короткие стрижки",
    "розовый",
    "trendy",
    "fashionista",
    "прически",
    "pastelhair",
    "Pelo",
    "волнистые волосы",
    "Бритая голова",
    "Rapada",
    "undershave",
    "hairfashion",
    "bob",
    "Бритая голова",
    "buzzed",
    "trendy",
    "bowlcut",
    "sidecut",
    "короткие волосы",
    "плетение",
    "косички",
    "фантастика",
    "светлые волосы",
    "undercut",
    "плетение волос",
    "крашеный",
    "блондинка",
    "прямые волосы",
    "красивая девушка",
    "amazing",
    "прически",
    "стрижки",
    "детские",
    "окрашевние",
    "прически",
    "стильные",
    "cool",
    "Красивые",
    "длинные волосы",
    "вечерние",
    "косы",
    "прически",
    "beauty",
    "короткие волосы",
    "girl",
    "Fashion",
    "прически",
    "кудри",
    "эксклюзивные",
    "не стандартные",
    "средние волосы",
    "netting",
    "на каждый день",
    "bunch",
    "свадьбные прически",
    "длинные волосы"
);
$deleting = array(
    "amaing",
    "amaizing",
    "beautiful hair",
    "beautifull girl",
    "beuty",
    "bradied hair",
    "brads",
    "caramel",
    "caramel hair",
    "child",
    "christmas",
    "curlygirl",
    "cutly hair",
    "eyeliner",
    "fresh",
    "fresh haircut",
    "g",
    "gif",
    "gitl",
    "green eyes",
    "ha",
    "hair colored",
    "hair colour",
    "hair cut",
    "hair fashion",
    "hair gif",
    "hair kids",
    "hair weave",
    "hairsyle",
    "high heel shoes",
    "high heels",
    "jeans pants",
    "kids hair",
    "ling hair",
    "make-up",
    "new year",
    "norway",
    "photography",
    "pink lips",
    "pink shoes",
    "pretty",
    "red lipstick",
    "Rihanna HairStyle",
    "shirts",
    "shoe",
    "snow",
    "snowy",
    "step by step",
    "sty",
    "style shoes model clothes fashion beautiful natural beauty dress skincare hair watches",
    "summer",
    "tattoos",
    "wavy",
    "wavyhair",
    "white dress",
    "20s",
    "africa",
    "afroamerican",
    "afrohair",
    "alcero",
    "alexandranewman",
    "alternative",
    "and",
    "apurado",
    "architecture",
    "arcoiris",
    "baldcat",
    "bat",
    "belleza",
    "bexbrent",
    "biba",
    "blackwomen",
    "blanca",
    "blau",
    "blode",
    "blondeangbrown",
    "blueandpink",
    "bocut",
    "boelcut",
    "bonhaircut",
    "bowlcuts",
    "bowlhead",
    "buuzed",
    "buzzcutfeed",
    "by",
    "bycraigchapman",
    "byhermizdaniel",
    "byjamesearnshaw",
    "bykjmsalons",
    "bymaurogalzingato",
    "bymichaelyoung",
    "bynicolasmyth",
    "byroyalshair",
    "bystreetfusion",
    "cabello",
    "cabelocurto",
    "californianas",
    "carr?",
    "carva",
    "cat",
    "chelseagirl",
    "chelseahair",
    "chelseahawk",
    "chop",
    "chopped",
    "classyprogressive",
    "cocoandbreezy",
    "coffiure",
    "colordy",
    "colorfullhair",
    "colors",
    "colour",
    "colours",
    "corte",
    "corto",
    "cosplay",
    "crazyhair",
    "crop",
    "davidbowie",
    "deanbradwey",
    "dipdown",
    "dj",
    "draw",
    "drawing",
    "dripped",
    "drop",
    "dyphair",
    "electronic",
    "enalind",
    "estilo",
    "extension",
    "extremehair",
    "eyebrows",
    "f1",
    "fabriziodelbuono",
    "fans",
    "fashionbydarrenbain",
    "fetish",
    "flower",
    "fluor",
    "frankapostolopoulos",
    "friends",
    "fuck",
    "galaxy",
    "girlfriends",
    "girls",
    "gothgirl",
    "greengirl",
    "haal",
    "haido",
    "hair:harryboocockandchrishorsmanforthehairstudio",
    "haircutgalaxy",
    "hairdolor",
    "hairred",
    "hairtatto",
    "hairtyle",
    "hairxutgalaxy",
    "half",
    "halfandhalfhair",
    "halfcolor",
    "halfhead",
    "halfshaved",
    "happy",
    "hardcore",
    "hare",
    "hayley",
    "hayleywilliam",
    "headashave",
    "headshavebaldbuzzed",
    "hooker",
    "ink",
    "inverted",
    "jaircut",
    "jaket",
    "joshuacongreve",
    "kaal",
    "karlymenzies",
    "katilinbelland",
    "katy",
    "kellyosbourne",
    "latex",
    "lego",
    "letsgetflashy.com",
    "lime",
    "linchestein",
    "long ",
    "look",
    "louisebrooks",
    "lupita",
    "lupitanyong",
    "make-upandstyling:justinecollins",
    "malevich",
    "margarita",
    "marilyn",
    "marine",
    "mermaidhairdontcare",
    "mia",
    "michellepargee",
    "mirandabanana",
    "mohican",
    "moniassemodel",
    "mowawk",
    "mullethair",
    "multi",
    "nadjagiramata",
    "napeshornapeshavedheadshavebaldbuzzednapeundercuthaircutundershaveshaving",
    "nekka",
    "nice",
    "nicolekae",
    "noeyebrows",
    "nohair",
    "nucarapada",
    "oldstyle",
    "oldwoman",
    "ombre",
    "onion",
    "original",
    "paramore",
    "pastelgoth",
    "paulmitchell",
    "peinado",
    "pelata",
    "peloliso",
    "pelorosa",
    "perfect",
    "perry",
    "photography:jimcrone",
    "pinkgirl",
    "pinkhairby",
    "pinkrihanna",
    "platinumhair",
    "pop",
    "products:goldwell",
    "punkgirl",
    "radical",
    "radicalook",
    "raspar",
    "razorshave",
    "reggae",
    "repost",
    "repostapp",
    "retrohair",
    "retrostyle",
    "riri",
    "rizado",
    "robertlobetta",
    "rock",
    "roots",
    "rosa",
    "rsasta",
    "saco",
    "sassoon",
    "scissors",
    "sculpture",
    "shavedside",
    "shavesides",
    "shirt",
    "shorhairdontcare",
    "shornna",
    "shortbackandsides",
    "shorthairbyalbertobaixaulinavarro",
    "shortnape",
    "si",
    "sideshaved",
    "silviagullongeatcut.gracias",
    "silviagullongracias",
    "skinedgirl",
    "skingbyrd",
    "slunksthanks",
    "smoke",
    "smoking",
    "spectacular",
    "straightcut",
    "stylecool",
    "stylehair",
    "submission",
    "sweet",
    "symmetric",
    "tazon",
    "thebaldmovement",
    "tomboylookswith",
    "topknot",
    "transitioncollection",
    "trends",
    "trenzas",
    "triforce",
    "trim",
    "turqoise",
    "turquoisehair",
    "utena",
    "video",
    "vimeo",
    "wet",
    "whiteonwhite",
    "whoistheauthor?tellme",
    "wig",
    "yolandi",
    "yolandivisser",
    "young",
    "zelda",
    "zgat",
    "zigzag",
    "bea",
    "black and white",
    "brown hair",
    "colored",
    "colored hair",
    "faahion",
    "fashion beautiful girl",
    "fashion tumblr",
    "gir",
    "green hair",
    "hair goals",
    "hairstyle fashion",
    "haistyle",
    "leather pants",
    "model",
    "nail polish",
    "red lips",
    "sports shoes",
    "tshirt",
    "afro",
    "aladdinsane",
    "amarillo",
    "androgyny",
    "blackhair",
    "blanco",
    "bowie",
    "braidideas",
    "brownhair",
    "byangeloseminara",
    "byissiechurcher",
    "cambiodelook",
    "chelseahaircut",
    "dark",
    "die",
    "died",
    "fashioncool",
    "flattop",
    "flowers",
    "gold",
    "greyhair",
    "hairdress",
    "makeover",
    "mermaid",
    "mitad",
    "mushroom",
    "music",
    "napeshaved",
    "nohairdontcare",
    "parrot",
    "pinkhairdontcare",
    "ponytail",
    "rasati",
    "rassata",
    "rasta",
    "shavinggirls",
    "shorthairdocare",
    "sides",
    "skinbird",
    "smooth",
    "twins",
    "undershaved",
    "verde",
    "xxlhair",
    "zero",
    "beautiful girls",
    "blue eyes",
    "eye makeup",
    "hairs",
    "hairstyles tumblr",
    "hairstyles tutorial",
    "hairstylist",
    "jeans",
    "moda",
    "tutorial",
    "azul",
    "baldbabe",
    "blackandblonde",
    "bleaching",
    "cabelos",
    "cheveuxcourts",
    "creative",
    "cut",
    "design",
    "elegant",
    "freckles",
    "halfhair",
    "halfkaal",
    "hayleywilliams",
    "hipster",
    "kale",
    "mermaidhair",
    "mullethawk",
    "nuca",
    "nude",
    "ornage",
    "pigtail",
    "rastas",
    "razor",
    "redhead",
    "rose",
    "sexy",
    "shave",
    "shorcut",
    "shorhair",
    "skingirl",
    "skinhead",
    "splithair",
    "beautiy",
    "blond hair",
    "grey hair",
    "lips makeup",
    "shoes",
    "shorts",
    "unique hairstyles",
    "bicolor",
    "brown",
    "buzzcutchallenge",
    "chelsea",
    "curl",
    "dyedhair",
    "goth",
    "hairdressers",
    "piercing",
    "Rihanna",
    "septum",
    "shavehead",
    "sideburns",
    "undecut",
    "yellowhair",
    "black hair",
    "color hair",
    "eyes makeup",
    "hair style tutorials",
    "hair styles tutorials",
    "careca",
    "cresta",
    "echonittolitto",
    "flatop",
    "issiechurcher",
    "mohawkhair",
    "pigtails",
    "shavedhair",
    "violethair",
    "baldwoman",
    "blondehair",
    "breezy",
    "buzz",
    "chelseacut",
    "coco",
    "darkhair",
    "dipdye",
    "hairderessing",
    "headtattoo",
    "shavednape",
    "whitehair",
    "shorts pants",
    "??",
    "assymetric",
    "baldisbeautiful",
    "bobstyle",
    "buzzcut",
    "curlyhair",
    "mohawkgirl",
    "punk",
    "turquoise",
    "ultrashort",
    "baggy pants",
    "fashion hair",
    "hair designs",
    "cabelo",
    "greenhair",
    "hawk",
    "orangehair",
    "shavedhead",
    "shorthaircut",
    "tondue",
    "dress",
    "hair tutorials",
    "messy hair",
    "afeitada",
    "haare",
    "invertedbob",
    "grey",
    "purple hair",
    "tumblr",
    "diphair",
    "purplehair",
    "shaving",
    "shornape",
    "violet",
    "lipstick",
    "black",
    "bluehair",
    "bobhair",
    "dreads",
    "glasses",
    "haar",
    "pastel",
    "redhair",
    "silver",
    "blue hair",
    "capellilunghi",
    "platinum",
    "rainbow",
    "te?ido",
    "hair design",
    "lips",
    "hairdressing",
    "mullet",
    "pixiehair",
    "shorts hair",
    "colorfull",
    "hairdresser",
    "halfandhalf",
    "pelolargo",
    "pink hair",
    "hairtattoo",
    "pixiecut",
    "curly",
    "shornnape",
    "woman",
    "bowlhaircut",
    "nape",
    "orange",
    "pixie",
    "hair tutorial",
    "red hair",
    "women hairstyles",
    "blackandwhite",
    "pants",
    "uniquehairstyles",
    "asymmetric",
    "pinkhair",
    "shortbangs",
    "straight hair",
    "EyeMakeUp",
    "Nail Color",
    "Nail Design",
    "NailDesign",
    "NailArt",
    "Nail",
    "Nail Art",
    "hairstyle tumblr",
    "Eyes",
    "Make Up",
    "MakeUp",
    "style",
    "Hair"
);
$connection = pg_connect("host=195.88.209.17 port=5432 dbname=makeup user=postgres password=12345_Vet");
$result = pg_query($connection, "SELECT tags,id FROM hairstyle LIMIT 1");
while ($row = pg_fetch_row($result)) {
    $sourceArray = explode(",", $row[0]);
    for($i = 0; $i < count($sourceArray); $i++) {
        $sourceArray[$i] = trim($sourceArray[$i]);
        print $sourceArray[$i].",";
    }
    for($i = 0; $i < count($sourceArray); $i++) {
        for ($j = 0; $j < count($deleting); $j++) {
            if ($sourceArray[$i] == $deleting[$j]) {
                $tempArrayEn[$i] = "";
            }
        }
    }
    print "<br>";
    for($i = 0; $i < count($sourceArray); $i++) {
        for ($j = 0; $j < count($eng); $j++) {
            if ($sourceArray[$i] == $eng[$j]) {
                $sourceArray[$i] = $rus[$j];
                print $sourceArray[$i].",";
            }
        }
    }

    //$query = pg_query("UPDATE hairstyle SET tags_ru='' WHERE id='$row[1]'");
    //if ($query) {
    ///    print "+++++++++++++++<br>";
    ///    print $row[0] . "<br>";
    //    print $ru . "<br>";
    //    $ru = "";
    //}
}
?>
</body>
</html>