<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
<?php
$eng = array(
    "3-d",
    "3d acrylic",
    "3d acrylic flowers",
    "3d bows",
    "3-d charms",
    "3d flower",
    "3d flowers",
    "3d mini nail art decoration",
    "3d nails",
    "3dart",
    "3dnails",
    "4d",
    "70s",
    "abstact",
    "abstract nail art",
    "abstract nails",
    "abstract neon nails",
    "abstreact",
    "acrylc",
    "acrylic",
    "acrylic and hand painted",
    "acrylic design",
    "acrylic glitter",
    "airbrush",
    "alice in wonderland",
    "almondshape",
    "alysnails",
    "america",
    "anchor",
    "animal",
    "animal nail art",
    "anime",
    "anniversary",
    "apple",
    "apple nails",
    "aqua",
    "aquarium",
    "ariel",
    "art deco",
    "art nail",
    "artistic colour gloss",
    "artistic nail designs",
    "artnail",
    "artscreens",
    "aurora",
    "autumnal",
    "awesome",
    "axxium",
    "aztec",
    "aztek",
    "baby blue",
    "babyboomer",
    "babyboomers",
    "balerine",
    "ball",
    "ballerina",
    "banana",
    "barbie",
    "barbie nails",
    "barbie pink",
    "barry m",
    "barrym",
    "base coat",
    "baseball",
    "batman",
    "baymax",
    "beach nails",
    "beach themed",
    "bees",
    "beige",
    "beige nails",
    "berry",
    "betty boop",
    "beverage",
    "beverages",
    "big",
    "bikinisoteeny",
    "bio seaweed gel",
    "bioseaweed gel",
    "bioseaweedgel",
    "black and gold",
    "black and yellow",
    "black matte",
    "black matte negativespace cham",
    "black white",
    "black widow",
    "blackdesign",
    "blogger",
    "blood",
    "blue and glitter",
    "blue and gold",
    "blue and red",
    "bluenails",
    "boat",
    "bohemian",
    "bone",
    "bones",
    "bonita",
    "books",
    "border",
    "born pretty",
    "bottle",
    "bows",
    "bridal nails",
    "bride",
    "bright",
    "bright colors",
    "bronze",
    "brush set design",
    "bug print",
    "buildergel",
    "bundle monster",
    "bunny",
    "butteflies",
    "butterflies",
    "butterfly",
    "butterfly nails",
    "cameocoral",
    "camo",
    "camouflage color",
    "candy",
    "candy cane",
    "candy corn",
    "cartoon",
    "cartoon characters",
    "cartoon nails",
    "cat",
    "catrice",
    "charms",
    "checkers",
    "cheetah",
    "cheetah print",
    "cherry",
    "cherry blossom",
    "chevron nails",
    "chic",
    "chilynn nails",
    "chinaglaze",
    "chocolate",
    "chrome",
    "chrome nails",
    "chrysanthemum",
    "chunky glitter",
    "cinderella",
    "circle",
    "circles",
    "classic",
    "classy",
    "claw",
    "clear",
    "cleveland cavaliers",
    "cnd",
    "coca-cola",
    "coconuts printed patterned",
    "coffee",
    "coffin mails",
    "coffin shaped",
    "coke",
    "color",
    "color blocking",
    "color change",
    "color club",
    "color outbreak",
    "colorcful",
    "colored acrylic",
    "colorful nail art",
    "colorful nails",
    "colors of the year",
    "colour blocking",
    "comic",
    "comma",
    "constellations",
    "contemporary",
    "contrast",
    "cooi 035",
    "cookies",
    "cool",
    "copper",
    "coral",
    "couples",
    "cracked ice",
    "cream",
    "creative",
    "crown",
    "crystals gelfrench",
    "cupcake",
    "cupcakes",
    "cupid",
    "cute polish",
    "cyclone",
    "daisies",
    "daisys",
    "dalek",
    "dana",
    "dana2",
    "dappled",
    "dark",
    "dark purple",
    "death star",
    "deathly",
    "decals",
    "decoration",
    "deer",
    "designs",
    "diamonds",
    "digi camo",
    "digital",
    "digital camouflage",
    "disney nail art",
    "disney nails",
    "disneyland",
    "diverse",
    "diy",
    "donut",
    "doraemon",
    "dotticure",
    "dotting",
    "draw",
    "drawing",
    "dreamcatcher",
    "drinks",
    "dripping",
    "dry",
    "dry brush",
    "dry brush nails",
    "dry marble",
    "drybrush",
    "ducks",
    "earthynails",
    "easter bunny",
    "easter nails",
    "easy",
    "easy nails",
    "edgy",
    "eggs",
    "egypt",
    "egyptian",
    "eiffel",
    "eiffel tower",
    "eiffel tower nail art",
    "el corazon nail polish",
    "elegant nail art",
    "elk",
    "ellen",
    "embellishments",
    "encapsulated",
    "essence",
    "eurofashion",
    "fade",
    "fairy dust",
    "fall nails",
    "false nails",
    "fashion nails",
    "feather",
    "feathers",
    "feet",
    "femme fatale",
    "festival",
    "festive",
    "festive nails",
    "film",
    "first time",
    "firtree",
    "fish",
    "fishnet",
    "fishtail manicure",
    "flames",
    "floral nails",
    "flower glitter",
    "flower wave",
    "folar",
    "food",
    "football",
    "forest",
    "fourth of july",
    "french manicure with colour",
    "french twist",
    "fresh nails",
    "fresh paint",
    "frills",
    "frosted",
    "frozen",
    "frozen nails",
    "fruit",
    "fruits",
    "full",
    "full color",
    "full nail wraps",
    "full nails",
    "fullcover",
    "funky fingers",
    "galaxies",
    "galaxy",
    "galaxy nail art",
    "galaxy nails",
    "garnet",
    "geeky",
    "geisha",
    "gel",
    "gel nailart",
    "gel polosh",
    "gel roses",
    "gelcolor",
    "geldesign",
    "gelfx",
    "gelpaint",
    "gemstones",
    "geometric",
    "geometrical",
    "gepard",
    "ghost",
    "glamour",
    "glamour design",
    "glass nails",
    "glitter french",
    "glitter gal",
    "glitter gradient",
    "glitter polish",
    "glitternails",
    "glitterpowder glitteracrylic",
    "glitters",
    "glossy",
    "gogoonly",
    "gold blue simple stamping",
    "gold leaf",
    "gold nails",
    "gold tips",
    "golden",
    "gore",
    "grain",
    "grass",
    "gray",
    "greece",
    "green and yellow",
    "green nails",
    "grey nails",
    "half moon",
    "halloween nails",
    "halloween skull spider nail ar",
    "hallows",
    "hand painte",
    "handmade",
    "handpainting",
    "hanukkah",
    "hard gel",
    "harry",
    "harry potter",
    "hawaii",
    "hello kitty nails",
    "hogwarts",
    "holidays",
    "holo",
    "holographic glitter",
    "holographic polish",
    "horror",
    "hot pink",
    "i scream nails",
    "ice",
    "ice cream",
    "icy",
    "image",
    "indian",
    "indigo",
    "inside out",
    "inspire",
    "inspired by pinterest",
    "instagram - cherry_nail_stud",
    "internnails",
    "iridescent",
    "iron man",
    "jade",
    "jamberry",
    "japan",
    "japanese",
    "japanese nail art",
    "japanese nails",
    "jewelry",
    "jewels",
    "julep",
    "kaleidoscope nail polish",
    "kawaii",
    "kiarasky",
    "kiaraskynails",
    "kids",
    "kiko",
    "kis",
    "kiss",
    "kissing",
    "kissing couples",
    "kiwi",
    "kleancolor",
    "konad",
    "konad stamp",
    "lace nails",
    "lavender",
    "leafy manicure",
    "leafy nails",
    "leaves",
    "lechat",
    "lemon",
    "letter",
    "light pink",
    "lilac",
    "lime green",
    "lines",
    "lion",
    "lips",
    "louisvuitton",
    "louisvuittonnails",
    "macaroon",
    "mandala",
    "manga",
    "mani",
    "marble nails",
    "marbled",
    "marbling",
    "mask",
    "masquerade",
    "matte nails",
    "mattenails",
    "mdu",
    "mermaid",
    "merry",
    "mesh",
    "metal",
    "metallic",
    "mickey",
    "mickey ears",
    "mickey mouse",
    "miffy",
    "milky",
    "milv",
    "minimalistic",
    "minion",
    "minions",
    "minnie mouse",
    "minnie mouse nails",
    "mint",
    "mirror",
    "mirror powder nails",
    "mirroreffect",
    "mix and match",
    "mixed",
    "mixed media",
    "modern",
    "modern french",
    "modern nails",
    "moka",
    "mom",
    "monochrome",
    "morgantaylor",
    "mothers day",
    "mouth",
    "movie",
    "movies",
    "moyou",
    "multichrome polish",
    "multicolor",
    "multicolored",
    "multycolor",
    "mundo de unas",
    "mundo de unas violet",
    "mundodeunas",
    "murals",
    "music",
    "mynails",
    "mysterious",
    "nageldesign bilder",
    "nail art",
    "nail art in dubai",
    "nail art stamp",
    "nail art stamping",
    "nail decoration",
    "nail foil",
    "nail max",
    "nail sticker",
    "nail vinyl",
    "nail vinyls",
    "nail wheel",
    "nail wrap",
    "naildecoration stickers",
    "nailjunkie",
    "nailmax",
    "nails leopard pink blue",
    "natural",
    "natural nail designs",
    "natural nails. fashion nails",
    "naturalnails",
    "nature",
    "navy",
    "navy blue",
    "neon nail art",
    "neon nails",
    "neon pink",
    "neonpink",
    "neons",
    "nerdy",
    "nerdy nails",
    "neutral",
    "new",
    "new retail",
    "newspaper nail art",
    "nice",
    "night",
    "nijntje",
    "no polish",
    "north shore glitter",
    "nsi",
    "nsp",
    "olaf",
    "olive",
    "ombre nails",
    "one finger different",
    "opi gel color",
    "opi sheer tints",
    "ornament",
    "ornaments",
    "owl",
    "paint splatter",
    "palm trees",
    "pantone",
    "paris",
    "paris nail design",
    "paris nailart",
    "paris nails",
    "parrot polish",
    "pastel nail art",
    "pastel nails",
    "pastels",
    "patchwork",
    "pattern",
    "patterned",
    "pavilion",
    "peacock",
    "peanuts nails",
    "pearl",
    "pearls",
    "pen",
    "personalized trees",
    "pigment",
    "pink and blue",
    "pink and purple",
    "pink and red",
    "pink and silver",
    "pink forever",
    "pink glitter",
    "pink nail art",
    "pinstripes",
    "pistachio color",
    "pizza",
    "plaid",
    "playing cards",
    "pointy",
    "pokemon",
    "poker",
    "polish",
    "polka dot",
    "poppy",
    "potter",
    "pressed glitter",
    "presto",
    "pretty",
    "princess",
    "print",
    "progel",
    "prom",
    "pueen",
    "pumpkin",
    "puns",
    "purple and blue nails",
    "purple nails",
    "qrs",
    "quilted nails",
    "rabbit",
    "rainbow honey",
    "rainbow nails",
    "ranails",
    "real nails",
    "rectangle",
    "red and gold",
    "red and white",
    "red nails",
    "red white and blue",
    "rednails",
    "redpolish",
    "reverse french",
    "reverse gradient",
    "reverse stamping",
    "revlon",
    "rhinestone nail art",
    "rhinestonenailart",
    "rhinrstones",
    "ring",
    "romantic",
    "rose",
    "royal blue",
    "royals baseball",
    "sally hansen",
    "saran wrap",
    "saran wrap nail art",
    "satin nail lacquer",
    "satin nails",
    "scary",
    "scotland plaid style",
    "scull",
    "sculpted",
    "sculpted acrylic",
    "sculpted gels",
    "sea",
    "sea horse",
    "sea shells",
    "seashell",
    "seashells",
    "sephora",
    "sephora by opi",
    "sequin",
    "sexy",
    "shaped",
    "sharp",
    "sharpie",
    "sharpies",
    "shattered glass",
    "sheet",
    "shell",
    "shells",
    "shimmer",
    "shine",
    "shinning",
    "shiny",
    "sinful",
    "sinful colors",
    "skeleton",
    "sky",
    "skyline",
    "slice",
    "slider design",
    "slime",
    "smile lines",
    "snake skin",
    "snoopy",
    "snoopy nails",
    "snowflake",
    "snupi",
    "soccer",
    "soccer nails",
    "soft looking",
    "solar",
    "space",
    "sparkles",
    "sparkling",
    "sparkly",
    "sparkly nails",
    "spider",
    "spiral",
    "splatter",
    "sponged technique",
    "sponging",
    "sports",
    "sports nails",
    "square",
    "square hue",
    "squirrel",
    "squoval",
    "ssm",
    "st. patricks day nails",
    "stainless",
    "stamped",
    "stamped nails",
    "stamping design",
    "stamping enchanted black anima",
    "stamping plates",
    "stampingnail",
    "star",
    "star wars",
    "starfish",
    "steam punk",
    "steel",
    "stencils",
    "sticker",
    "stilettoshape",
    "stone marble",
    "stones",
    "strass",
    "strip",
    "striped",
    "stripers",
    "striping",
    "studded nails",
    "sugaring",
    "summercrush",
    "summernails",
    "sunflower design",
    "sunny",
    "sunset",
    "superhero",
    "superman",
    "swan tutorial",
    "swatch",
    "sweater nails",
    "sweet",
    "swirl",
    "swirls",
    "symbol",
    "take your time gel indigo",
    "tan",
    "tape mani",
    "tape nail art",
    "tape nailart",
    "tattoos",
    "template",
    "template image plate",
    "tet celebrate",
    "thenailprince",
    "thenailprince andyhaidinh n",
    "thermal",
    "thin",
    "thumper bunny",
    "tie dye",
    "tip",
    "toenail art",
    "topnails",
    "triangle",
    "tribal",
    "tribal nails",
    "triple stamp",
    "trumpgel usa",
    "tuples",
    "twinkledt",
    "twobirdslacquer",
    "uber chic",
    "uber chic 7-02",
    "uberchic",
    "uberchicbeauty",
    "ugly sweater",
    "unicorn",
    "unique",
    "useful",
    "uv gel",
    "valentine",
    "valentine lips kiss pink neon",
    "vetrousa",
    "vintage",
    "vinyl",
    "vinyls",
    "vinylux",
    "violet",
    "volishpolish",
    "water",
    "water droplet",
    "water spotting",
    "watercolor",
    "watercolor nails",
    "watercolor painting",
    "watermarble",
    "watermarble nails",
    "watermelon",
    "waterspotted",
    "wave",
    "wedding",
    "wedding nails",
    "wet n wild",
    "wheel",
    "white french",
    "wing",
    "witch",
    "wonder woman",
    "wraps",
    "yarn",
    "yeg",
    "yellow nail art",
    "young nails spakle",
    "yvesswiss",
    "zircon",
    "nail art design",
    "hand-painted",
    "gel-polish",
    "glitter",
    "gel nails",
    "yagala",
    "nail design",
    "stamping",
    "stamping nail art",
    "pink",
    "nail fashion",
    "valentines day",
    "trendy",
    "abstract",
    "gel polish",
    "black",
    "blue",
    "nail polish",
    "white",
    "ombre",
    "nailart",
    "gel design",
    "french",
    "purple",
    "floral",
    "red",
    "christmas",
    "flowers",
    "fashion",
    "natural nails",
    "acrylic nails",
    "gold",
    "freehand",
    "summer nails",
    "stiletto nails",
    "french manicure",
    "holiday",
    "hand painted",
    "swarovski",
    "gelish",
    "green",
    "gradient nails",
    "animals",
    "gel art",
    "beautiful",
    "gradient",
    "pretty nails",
    "beauty",
    "glitter fade",
    "swarovski crystals",
    "nude nails",
    "st patricks day",
    "nude",
    "coffin nails",
    "opi",
    "glitter nails",
    "matte",
    "bornprettystore",
    "neon colors",
    "ombre nail art",
    "summer",
    "neon",
    "yellow",
    "roses",
    "halloween",
    "silver",
    "chevron",
    "pedicure",
    "stiletto",
    "black and white",
    "bridal",
    "stripes",
    "almond nails",
    "tropical",
    "winter nails",
    "short nails",
    "cartoons",
    "3d",
    "blue nails",
    "cute nails",
    "water marble",
    "studs",
    "toe nail art",
    "dots",
    "long nails",
    "3d nail art",
    "flower",
    "orange",
    "spring nails",
    "acrylic paint",
    "glitter gel",
    "shellac",
    "art",
    "cute",
    "beach",
    "essie",
    "almond shape",
    "brown",
    "summer design",
    "christmas nails",
    "easy nail art",
    "floral nail art",
    "love",
    "winter",
    "colorful",
    "animal print",
    "china glaze",
    "heart",
    "leopard print",
    "sparkle",
    "water decals",
    "bling nails",
    "pastel",
    "simple design",
    "bling",
    "grey",
    "lace nail art",
    "matte top coat",
    "trendy nail art",
    "nail stamping",
    "pink nails",
    "abstract design",
    "holographic",
    "marble",
    "rhinestones",
    "coffin",
    "cute nail art",
    "gel manicure",
    "hearts",
    "acrylic full set",
    "polka dots",
    "simple",
    "spring",
    "una",
    "kaleidoscope",
    "rainbow",
    "stilettos",
    "striping tape",
    "glitter acrylic",
    "hand painted flowers",
    "notd",
    "pink & whites",
    "accent nail",
    "fall",
    "naildesign",
    "silver glitter",
    "fall colors",
    "toenails",
    "gelnails",
    "bow",
    "floral hand painted",
    "gel nails and art",
    "happy",
    "lace",
    "painted",
    "stars",
    "woman",
    "4th of july",
    "airbrushed",
    "disney",
    "nails art",
    "french tip",
    "gel color",
    "zebra",
    "leopard",
    "snowflakes",
    "elegant",
    "fake nails",
    "fall nail art",
    "gold glitter",
    "mint green",
    "orly",
    "stickers",
    "black nails",
    "negative space",
    "peach",
    "pink and black",
    "stamp",
    "easter",
    "gelpolish",
    "gold and black",
    "ocean",
    "blue glitter",
    "christmas tree",
    "crystals",
    "fun",
    "gel overlay",
    "girly",
    "handpainted",
    "multi colored",
    "new year nails",
    "solar nails",
    "acrylicnails",
    "almond",
    "blue and white",
    "foils",
    "nail wraps",
    "one stroke",
    "square nails",
    "turquoise",
    "vacation",
    "acrylics",
    "autumn",
    "french tips",
    "palm tree",
    "red and black",
    "rhinestone"
);
$rus = array(
    "3-d",
    "3d акрил",
    "3d акриловые цветы",
    "3d бантики",
    "3-D шармы",
    "3d цветок",
    "3d цветы",
    "3d мини украшения ногтей",
    "3d ногти",
    "3d рт",
    "3d ногти",
    "4d",
    "70-е",
    "абстракт",
    "абстрактный дизайн",
    "абстрактный дизайн",
    "абстрактные неоновые ногти",
    "абстракт",
    "акрил",
    "акрил",
    "акриловые с ручной росписью",
    "акриловый дизайн",
    "акриловый блеск",
    "аэрограф",
    "Алиса в стране чудес",
    "миндалевидная форма",
    "alysnails",
    "Америка",
    "якорь",
    "животное",
    "животные на ногтях",
    "аниме",
    "Годовщина",
    "яблоко",
    "яблочные ногти",
    "вода",
    "аквариум",
    "Ariel",
    "арт-деко",
    "искусство ногтей",
    "художественный глянец",
    "художественные дизайн ногтей",
    "дизайн ногтей",
    "artscreens",
    "северное сияние",
    "осенний",
    "здорово",
    "axxium",
    "ацтеки",
    "ацтеки",
    "голубые",
    "babyboomer",
    "babyboomers",
    "балерина",
    "мяч",
    "балерина",
    "банан",
    "Барби",
    "Барби ногти",
    "Барби розовый",
    "barry m",
    "barrym",
    "основа",
    "бейсбол",
    "Бэтмен",
    "baymax",
    "пляжные ногти",
    "пляжные ногти",
    "пчелы",
    "бежевый",
    "бежевые ногти",
    "ягода",
    "Betty Boop",
    "напиток",
    "напитки",
    "большой",
    "bikinisoteeny",
    "био-гель из морских водорослей",
    "био-гель из морских водорослей",
    "био-гель из морских водорослей",
    "черный и золотой",
    "черный и желтый",
    "черный матовый",
    "черный матовый",
    "черно-белый",
    "черная вдова",
    "черный дизайн",
    "блоггер",
    "кровь",
    "синий и блестки",
    "синий и золотой",
    "синий и красный",
    "голубые ногти",
    "лодка",
    "богемский",
    "кость",
    "кости",
    "Bonita",
    "книги",
    "граница",
    "born pretty",
    "бутылка",
    "банты",
    "свадебные ногти",
    "невеста",
    "яркий",
    "яркие цвета",
    "бронза",
    "набор кистей дизайн",
    "ошибка печати",
    "гель для наращивания",
    "bundle monster",
    "кролик",
    "butteflies",
    "бабочки",
    "бабочка",
    "бабочки ногти",
    "cameocoral",
    "камуфляж",
    "камуфляж цвет",
    "конфеты",
    "конфета",
    "сладкий попкорн",
    "мультфильм",
    "герои мультфильмов",
    "мультфильм ногти",
    "Кот",
    "Catrice",
    "Чары",
    "шашки",
    "гепард",
    "гепард печати",
    "вишня",
    "вишня в цвету",
    "шеврон ногти",
    "шик",
    "chilynn nails",
    "chinaglaze",
    "шоколад",
    "хром",
    "хромовые ногти",
    "хризантема",
    "чакки блестки",
    "Золушка",
    "круг",
    "круги",
    "классический",
    "классный",
    "коготь",
    "Чисто",
    "cleveland cavaliers",
    "CND",
    "Кока-Кола",
    "кокосы напечатаные",
    "кофе",
    "coffinnails",
    "coffin shaped",
    "кокс",
    "цвет",
    "цвет блокировка",
    "изменение цвета",
    "цвет клуб",
    "цвет вспышки",
    "цветные",
    "цветные акриловые",
    "красочные искусства ногтя",
    "красочные ногти",
    "Цвета года",
    "цвет блокировка",
    "косметик",
    "запятая",
    "созвездий",
    "современный",
    "контраст",
    "cooi 035",
    "печенье",
    "круто",
    "медь",
    "коралловый",
    "пары",
    "трещины на льду",
    "крем",
    "творческий",
    "корона",
    "кристаллы gelfrench",
    "кекс",
    "кексы",
    "купидон",
    "милыйлак",
    "циклон",
    "маргаритки",
    "daisys",
    "dalek",
    "Dana",
    "dana2",
    "пестрый",
    "темно",
    "темно фиолетовый",
    "звезда Смерти",
    "смертельно",
    "отличительные знаки",
    "украшение",
    "олень",
    "конструкции",
    "бриллианты",
    "пиксельный камуфляж",
    "пиксельный камуфляж",
    "пиксельный камуфляж",
    "Disneyland",
    "Disneyland",
    "Disneyland",
    "разнообразный",
    "поделки",
    "пончик",
    "Doraemon",
    "точечный дизайн",
    "точечный дизайн",
    "привлечь",
    "Рисование",
    "Ловец снов",
    "напитки",
    "dripping",
    "сухой",
    "сухая кисть",
    "сухой щеткой ногти",
    "сухой мрамор",
    "сухая кисть",
    "уток",
    "полированные",
    "Пасхальный заяц",
    "пасхальные ногти",
    "легко",
    "легкие ногти",
    "раздражительный",
    "яйца",
    "Египет",
    "египтянин",
    "Эйфелева Башня",
    "Эйфелева башня",
    "Эйфелева Башня",
    "Corazon",
    "элегантный ногтей",
    "лось",
    "Эллен",
    "украшение",
    "encapsulated",
    "essence",
    "EuroFashion",
    "fade",
    "волшебная пыль",
    "fall nails",
    "накладные ногти",
    "стильные ногти",
    "перья",
    "перья",
    "ноги",
    "роковая женщина",
    "фестиваль",
    "праздничный",
    "праздничные ногти",
    "фильм",
    "начало",
    "ель",
    "рыба",
    "рыболовная сеть",
    "Фиштейл маникюр",
    "огонь",
    "цветочные ногти",
    "цветок блестки",
    "цветок волна",
    "folar",
    "еда",
    "футбол",
    "лес",
    "4 july",
    "французский маникюр с цветом",
    "французский твист",
    "свежие ногти",
    "Свежая краска",
    "выкрутасы",
    "матовый",
    "оледеневшие",
    "замороженные ногти",
    "фрукты",
    "фрукты",
    "полный",
    "полноцветный",
    "полные обертывания для ногтей",
    "полные ногти",
    "fullcover",
    "funky fingers",
    "галактик",
    "галактик",
    "галактик",
    "галактик",
    "гранат",
    "вызывающим",
    "гейша",
    "гель",
    "gelnailart",
    "gel polosh",
    "gel roses",
    "gelcolor",
    "geldesign",
    "gelfx",
    "gelpaint",
    "драгоценные камнями",
    "геометрия",
    "геометрия",
    "Гепард",
    "призрак",
    "очарование",
    "гламурный дизайн",
    "стеклянные ногти",
    "блестки французский",
    "glitter gal",
    "градиент блестки",
    "польский блеск",
    "glitternails",
    "glitterpowder glitteracrylic",
    "glitters",
    "глянцевый",
    "gogoonly",
    "золотой синий простой стемпинг",
    "сусальное золото",
    "золотые ногти",
    "золотые уроки",
    "золотой",
    "gore",
    "зерно",
    "трава",
    "серый",
    "Греция",
    "зеленый и желтый",
    "зеленые ногти",
    "серые ногти",
    "луна",
    "Хэллоуин",
    "Хэллоуин череп паук",
    "hallows",
    "рука painte",
    "ручная работа",
    "ручная работа",
    "ханука",
    "твердый гель",
    "Гарри Поттер",
    "Гарри Поттер",
    "Гавайи",
    "Hello Kitty ",
    "Хогвартс",
    "выходные",
    "голографический блеск",
    "голографический блеск",
    "голографический лак",
    "ужастики",
    "ярко-розовый",
    "scream",
    "лед",
    "мороженое",
    "ледяной",
    "образ",
    "индийский",
    "индиго",
    "наизнанку",
    "вдохновлять",
    "вдохновленный Pinterest",
    "Instagram - cherry_nail_stud",
    "internnails",
    "радужный",
    "Железный человек",
    "нефрит",
    "jamberry",
    "Япония",
    "Япония",
    "Япония",
    "Япония",
    "драгоценности",
    "драгоценности",
    "julep",
    "Калейдоскоп лак",
    "kawaii",
    "kiarasky",
    "kiarasky",
    "Дети",
    "kiko",
    "поцелуй",
    "поцелуй",
    "поцелуй",
    "поцелуй",
    "киви",
    "kleancolor",
    "Konad",
    "Konad стемпинг",
    "кружева ногти",
    "лаванда",
    "листья",
    "листья",
    "листья",
    "LeChat",
    "лимон",
    "письмо",
    "светло-розовый",
    "сирень",
    "зеленый лайм",
    "линии",
    "лев",
    "губы",
    "Louis Vuitton",
    "Louis Vuitton",
    "макаруны",
    "мандала",
    "манга",
    "мани",
    "мраморные ногти",
    "мраморное",
    "окраска под мрамор",
    "маска",
    "маскарад",
    "матовые ногти",
    "матовые ногти",
    "mdu",
    "Русалка",
    "веселый",
    "сетка",
    "металл",
    "металлический",
    "mickey mouse",
    "Mickey уши",
    "mickey mouse",
    "Miffy",
    "молочный",
    "milv",
    "минималистичный",
    "миньоны",
    "миньоны",
    "minnie mouse",
    "minnie mouse",
    "мята",
    "зеркало",
    "зеркало порошок",
    "зеркальный эффект",
    "смешанный",
    "смешанный",
    "смешанная техника",
    "современный",
    "современный френч",
    "современный",
    "moka",
    "Мама",
    "монохромный",
    "morgantaylor",
    "день матери",
    "рот",
    "кино",
    "кино",
    "moyou",
    "multichrome",
    "многоцветный",
    "многоцветный",
    "многоцветный",
    "mundo de unas",
    "mundo de unas",
    "mundodeunas",
    "фрески",
    "Музыка",
    "мои ногти",
    "загадочный",
    "nageldesign",
    "маникюр",
    "ногтей в Дубайи",
    "стемпинг",
    "стемпинг",
    "украшения ногтей",
    "фольга для ногтей",
    "max",
    "наклейки на ногти",
    "лак для винила",
    "лак для винила",
    "набор для  ногтей",
    "набор для  ногтей",
    "наклейки naildecoration",
    "nailjunkie",
    "nailmax",
    "леопард  розовый синий",
    "натуральный",
    "натуральный",
    "натуральный",
    "натуральный",
    "природа",
    "морской",
    "темно-синий",
    "неоновый маникюр",
    "неоновые ногти",
    "неоноворозовый",
    "неоноворозовый",
    "неоновые",
    "всезнайка",
    "nerdy ",
    "нейтральный",
    "новый",
    "новый розничный",
    "газетный дизайн",
    "хороший",
    "ночь",
    "nijntje",
    "без лака",
    "north shore",
    "NSI",
    "nsp",
    "Olaf",
    "оливковый",
    "ombre",
    "один палец отличается",
    "OPI",
    "opi ",
    "орнамент",
    "украшения",
    "сова",
    "краска брызгами",
    "пальмовые деревья",
    "Pantone",
    "Париж",
    "Париж",
    "Париж",
    "Париж",
    "попугай",
    "пастели",
    "пастели",
    "пастели",
    "patchwork",
    "шаблон",
    "узорный",
    "павильон",
    "павлин",
    "арахис",
    "жемчуг",
    "жемчуг",
    "ручка",
    "деревья",
    "пигмент",
    "розовый и голубой",
    "розовый и фиолетовый",
    "розовый и красный",
    "розовый и серебристый",
    "розовый навсегда",
    "розовый блеск",
    "розовый",
    "тонкие полосы",
    "фисташковый ",
    "пицца",
    "плед",
    "игральные карты",
    "заостренный",
    "покемон",
    "покер",
    "polish",
    "в горошек",
    "мак",
    "гончар",
    "засушенный блестки",
    "престо",
    "Симпатичные",
    "принцесса",
    "принт",
    "progel",
    "выпускной вечер",
    "pueen",
    "тыква",
    "каламбуров",
    "фиолетовые и синие ногти",
    "фиолетовые ногти",
    "квартерам",
    "стеганые ногти",
    "кролик",
    "радуга И  мед",
    "радугА",
    "ranails",
    "свои ногти",
    "прямоугольник",
    "красный и золотой",
    "красный и белый",
    "красные",
    "красный Белый и синий",
    "красные",
    "красные",
    "обратный французский",
    "обратный градиент",
    "обратная стемпинг",
    "Revlon",
    "горный хрусталь",
    "горный хрусталь",
    "горный хрусталь",
    "кольцо",
    "романтический",
    "Роза",
    "Королевский синий",
    "Члены королевской семьи бейсбол",
    "Sally Hansen",
    "Saran Wrap",
    "Saran Wrap",
    "сатин лак для ногтей",
    "атласные ногти",
    "страшно",
    "шотландский стиль",
    "череп",
    "скульптор",
    "скульптор",
    "скульптор",
    "море",
    "морской конек",
    "морские раковины",
    "морская ракушка",
    "морская ракушка",
    "Sephora",
    "Sephora от OPI",
    "цехин",
    "секси",
    "фасон",
    "шарпи",
    "шарпи",
    "шарпи",
    "шарпи",
    "лист",
    "шелл",
    "шелл",
    "шиммер",
    "блеск",
    "шининг",
    "блестящий",
    "sinful",
    "sinful",
    "скелет",
    "небо",
    "skyline",
    "кусочек",
    "слайдер",
    "слим",
    "слимлайн",
    "змеиная кожа",
    "Снупи ногти",
    "Снупи ногти",
    "снежинка",
    "Снупи ногти",
    "футбольный",
    "футбольный",
    "мягкая выглядящий",
    "солнечный",
    "космос",
    "блестки",
    "сверкающий",
    "блестящие",
    "блестящие",
    "паук",
    "спираль",
    "брызги",
    "спонж",
    "спонж",
    "спорт",
    "спорт",
    "квадрат",
    "квадрат",
    "белка",
    "squoval",
    "SSM",
    "святой патрик",
    "нержавеющий",
    "стемпинг",
    "стемпинг",
    "стемпинг",
    "стемпинг",
    "стемпинг",
    "стемпинг",
    "звезда",
    "Звездные войны",
    "морская звезда",
    "стимпанк",
    "сталь",
    "трафареты",
    "наклейка",
    "стилеты",
    "мрамор",
    "камни",
    "страз",
    "полоски",
    "полоски",
    "stripers",
    "striping",
    "шипы",
    "мармеладные",
    "summercrush",
    "summercrush",
    "подсолнухи",
    "солнечный",
    "закат солнца",
    "супергерой",
    "superman",
    "лебедь",
    "swatch",
    "вязанный дизайн",
    "sweet",
    "Водоворот",
    "Водоворот",
    "символ",
    "гель индиго",
    "загар",
    "tape",
    "tape",
    "tape",
    "тату",
    "трафарет",
    "трафарет",
    "Tet отмечают",
    "эффект пузырьков",
    "эффект пузырьков",
    "thermal",
    "тонкий",
    "thumper bunny",
    "галстук",
    "наконечник",
    "педикюр",
    "topnails",
    "треугольник",
    "африканский стиль",
    "африканский стиль",
    "африканский стиль",
    "trumpgel",
    "tuples",
    "twinkled t",
    "two birds lacquer",
    "uber chic",
    "uber chic",
    "uber chic",
    "uber chic",
    "ugly sweater",
    "единорог",
    "уникальный",
    "полезным",
    "уф гель",
    "Валентин",
    "Валентин",
    "vetro",
    "марочный",
    "винил",
    "винилы",
    "vinylux",
    "Фиолетовый",
    "volish polish",
    "водный маникюр",
    "капли воды",
    "водный маникюр",
    "акварель",
    "акварель",
    "акварель",
    "разводы на воде",
    "разводы на воде",
    "арбуз",
    "водный маникюр",
    "волна",
    "свадьба",
    "свадьба",
    "мокрый п дикий",
    "колесо",
    "белый френч",
    "крыло",
    "ведьма",
    "удивительная женщина",
    "обертывания",
    "пряжа",
    "YEG",
    "желтый ногтей",
    " spakle",
    "yves swiss",
    "циркон",
    "дизайн ногтей",
    "ручная роспись",
    "гель",
    "глиттер",
    "гель",
    "yagala",
    "дизайн ногтей",
    "стемпинг",
    "стемпинг",
    "розовый",
    "fashion",
    "День Святого Валентина",
    "тренди",
    "Абстрактные",
    "гель",
    "черный",
    "синий",
    "polish",
    "белый",
    "омбре",
    "маникюр",
    "гель",
    "френч",
    "пурпурный",
    "цветочный",
    "красный",
    "новый год",
    "цветы",
    "мода",
    "натуральные ногти",
    "акриловые ногти",
    "золото",
    "freehand",
    "лето",
    "стилеты",
    "френч",
    "праздничный",
    "ручная роспись",
    "сваровски",
    "Gelish",
    "зеленый",
    "градиент",
    "животные",
    "гель",
    "красивые",
    "градиент",
    "красивые",
    "красивые",
    "глиттер",
    "Сваровски",
    "телесного цвета",
    "День Святого Патрика",
    "телесного цвета",
    "гробов ногти",
    "OPI",
    "глиттер",
    "матовые",
    "born pretty store",
    "неоновые",
    "омбре",
    "лето",
    "неоновые",
    "желтые",
    "розы",
    "Хэллоуин",
    "Серебро",
    "шеврон",
    "педикюр",
    "стилет",
    "черное и белое",
    "свадебный",
    "полосы",
    "миндальные ногти",
    "тропический",
    "зима",
    "короткие ногти",
    "мультфильмы",
    "3d",
    "голубые",
    "милые",
    "вода мрамор",
    "шпильки",
    "studs",
    "точки",
    "длинные",
    "3d искусства ногтя",
    "цветы",
    "оранжевый",
    "весна",
    "акрил",
    "гель с блестками",
    "шеллак",
    "арт",
    "милый",
    "пляж",
    "essie",
    "миндалевидные",
    "коричневый",
    "летний дизайн",
    "новый год",
    "простые",
    "цветочный дизайн",
    "love",
    "зима",
    "цветные",
    "животные",
    "china glaze",
    "сердце",
    "Леопардовый рисунок",
    "sparkle",
    "вода",
    "Bling",
    "пастель",
    "простые",
    "bling",
    "серый",
    "кружева",
    "матовый верхний слой",
    "тренди",
    "стемпинг",
    "розовые",
    "абстрактный дизайн",
    "голографический",
    "мрамор",
    "стразы",
    "coffin",
    "милые",
    "гель",
    "сердца",
    "акрил",
    "горошек",
    "простые",
    "весна",
    "una",
    "калейдоскоп",
    "радуга",
    "стилеты",
    "ленты",
    "акриловый блеск",
    "ручная роспись цветы",
    "notd",
    "розовый и белые",
    "акцент ногтей",
    "падать",
    "Naildesign",
    "серебряный блеск",
    "осенние краски",
    "педикюр",
    "гель",
    "bow",
    "ручная роспись цветы",
    "гель",
    "happy",
    "кружева",
    "ЧЕЛЛЕНДЖ",
    "звезды",
    "женщина",
    "4 июля",
    "аэрографом",
    "дисней",
    "дизайнерские",
    "френч",
    "гель",
    "зебра",
    "леопард",
    "снежинки",
    "элегантный",
    "накладные ногти",
    "fall ",
    "золотой блеск",
    "мятно-зеленый",
    "orly",
    "наклейки",
    "черные ногти",
    "черно белые",
    "персик",
    "розовый и черный",
    "стемпинг",
    "Пасха",
    "гель",
    "золотой и черный",
    "океан",
    "синий блеск",
    "новогодняя елка",
    "кристаллы",
    "весело",
    "гель",
    "девчячий",
    "ручная роспись",
    "разноцветные",
    "новый год",
    "солнечные ",
    "акрил",
    "миндальный",
    "синий и белый",
    "foils",
    "обертывание",
    "роспись",
    "квадратные ногти",
    "бирюзовый",
    "отпуск",
    "акрил",
    "осень",
    "френч",
    "Пальма",
    "красный и черный",
    "горный хрусталь"
);
$deleting = array(
    "gingerbread",
    "@nailstamp @nails @black&white",
    "@__justkiss",
    "@kerajohnson311",
    "@thanailsurgeon",
    "@__thenaildiva",
    "@nailsby_nellieb",
    "@iluvurnailz",
    "@nailsbymztina",
    "@alysnails",
    "shamrock",
    "green and gold",
    "fito",
    "gifts",
    "oil",
    "russia",
    "nailsntna",
    "ntnasimone",
    "pinknailsacrylicgelnewcu",
    "ruffian nails",
    "real flowers",
    "basket weaves",
    "ghzel",
    "burnt paper",
    "wow",
    "peace",
    "taped nail art",
    "nails manicure",
    "how to",
    "school",
    "xmas nails",
    "misletoe",
    "blocking",
    "big5free",
    "non-toxic",
    "lovemynails",
    "naildecals",
    "artistic vortex pattern",
    "foliage",
    "plants",
    "dainty",
    "watercolors",
    "tv show",
    "friends",
    "water color",
    "henna tattoo",
    "tiffany blue",
    "crystal pixie",
    "young nails maniq",
    "dog",
    "valentine day",
    "negle tipper",
    "negle produkter",
    "uv gele",
    "halloween nail design",
    "mermaidbluenailartlongnails",
    "nail swag",
    "hard gel overlay",
    "jazzyreynbownails",
    "almond-shaped",
    "monroe nails",
    "nail bling",
    "nail pearls",
    "ladyqueen",
    "goldenleaves",
    "leavesnail",
    "goldennail",
    "ohnailyoudidnt",
    "gelishmintofspring",
    "gelishcleanslate",
    "marlbling",
    "colors",
    "sharpie marbling",
    "orang",
    "notes",
    "etnic",
    "disco nails",
    "disco ball",
    "starry",
    "full nail sticker",
    "christmas gift",
    "hand painted nail art",
    "boost gel",
    "gradieng nails",
    "lacquer legion",
    "skittles",
    "joyme",
    "opi color paints",
    "color paints",
    "floral habd painted",
    "double stamped",
    "nobility",
    "le chat",
    "gel marble",
    "classic red",
    "pink and gold",
    "fashion nails. young nails",
    "french maniure",
    "one stroke flowers",
    "back to school",
    "nail stencil",
    "harry potty",
    "rosegold",
    "water matble",
    "dried flowers",
    "dry flowers",
    "nailsgantshill",
    "gantshill naiilseastlondon",
    "decal stamping",
    "perfume",
    "occitan",
    "psychedelic",
    "sixities",
    "60s",
    "valentines nails",
    "festival nails",
    "coachella",
    "coachella nails",
    "snow flakes",
    "meant",
    "typhoon",
    "thermo gel",
    "bsg",
    "bsgfanwork",
    "lime",
    "studded",
    "gems nail art",
    "batman nails",
    "broken ornaments",
    "summer drinks",
    "organicnails",
    "tiger nail art",
    "tiger nails",
    "tiger water decals",
    "puzzle nails",
    "crisp",
    "color show",
    "graveyard",
    "snakes",
    "gel foil",
    "jewellery",
    "pandora",
    "foil design",
    "folk art.",
    "woven",
    "braided",
    "professional",
    "dramatic",
    "nailart nailartclub nailart",
    "dangle",
    "prom nails",
    "silhouette nails",
    "watermelonnails",
    "orangenails",
    "tapemani",
    "sallyhansen nails nailart",
    "stiches",
    "fruitnails",
    "abstract black and white",
    "black and blue",
    "one step gel polish",
    "purjoi nail studio one step ge",
    "salon gels",
    "purjoi",
    "soak off",
    "diy nail decal",
    "cancer",
    "fall leaf",
    "3d leaf",
    "glitter tips",
    "flowers.stripes.",
    "skull nails",
    "stripe",
    "newhalloweendesigns",
    "skeletonnails",
    "gel paint",
    "bubbles",
    "sparkling garbage",
    "sailor",
    "pinstripe",
    "gel acrylic",
    "cherry red",
    "stilletto nails",
    "banana republic",
    "detailed",
    "henna nail art",
    "wheat",
    "maya",
    "asymmetric",
    "amazing",
    "fox",
    "wood",
    "more neons",
    "pklka dots",
    "neon stripes",
    "net technique",
    "elegant glass nails",
    "additives",
    "nailsnailgamenailartloveg",
    "fushia",
    "flossgloss",
    "nailartdecoration",
    "starbucks",
    "nailgraffiti",
    "onyxbrands",
    "beautyintherock",
    "3d gele",
    "darling diva",
    "darling diva anna",
    "darling diva royale",
    "seahorse",
    "waterdecals",
    "summernail",
    "floralnail",
    "fail",
    "tony moly",
    "texans",
    "nfl nails",
    "beetle",
    "flowers nail art",
    "summer tor nail art",
    "beach toe nails",
    "nail art tutorial",
    "asian nail art",
    "girlie",
    "black stripe",
    "kpop nails",
    "splatter nail art",
    "pink toenails",
    "tradional nail art",
    "summer toe nail art",
    "hallyu nail art",
    "sheer nail art",
    "nc.a im different nails",
    "queen elsa",
    "panthers",
    "kitty",
    "dragonfly",
    "toenail",
    "tuxedo",
    "trump gel usa",
    "party",
    "fire nails",
    "sweets",
    "purple and pink",
    "stamping nail",
    "bp02",
    "jewellery nail art training",
    "mixed colours",
    "animal print nail art",
    "holo nails",
    "holo nail art",
    "holo gradient",
    "tie&dye",
    "glitzy nails",
    "loop",
    "bio sculpture gel",
    "mad hatter",
    "hernailsrock",
    "marmaid",
    "nude and black",
    "burberry",
    "opi gelcolor",
    "trip",
    "travel",
    "annapolis",
    "digit-al dozen",
    "fingerfood",
    "floss gloss",
    "flip flops",
    "sailing",
    "tart deco",
    "haute as hello",
    "surfing",
    "surf",
    "nail artist",
    "toes",
    "young nails",
    "mydesigns4you",
    "el corazon",
    "4th of july",
    "nail designs",
    "",
    "wave goddess",
    "surf board",
    "surf chick",
    "presto gel",
    "sechevite",
    "sponge shading",
    "christmas tree lights",
    "tree lights",
    "beachy",
    "red tips",
    "textured nails",
    "vtutorial",
    "summer beach",
    "lemon and limes",
    "3d acrylic bows",
    "frech acrylic",
    "betty boop nails",
    "bettyboop",
    "snow white",
    "cocaine nails",
    "textured nail",
    "trinidad and tobago",
    "trini",
    "trinbago",
    "3d nail art design",
    "redwhiteandblack",
    "patrick",
    "sponge bob",
    "spongebob nails",
    "emilio ramos",
    "kermit",
    "trick or treat",
    "friend",
    "palm",
    "mine",
    "first manicure",
    "zebra. zebra print",
    "gift",
    "christmastree",
    "striped nail art",
    "cool colors",
    "green and turquoise",
    "game inspired",
    "graffiti nail art",
    "death",
    "life",
    "long acrylic nails",
    "spongebob",
    "spongebob squarepants",
    "white nail art",
    "encapsulated acrylic",
    "galaxy. glitter",
    "space nails",
    "womans face",
    "men",
    "bubble gum princess",
    "cookie monster nails",
    "games",
    "super mario bros",
    "nicolebyopi",
    "sandtropez",
    "chile",
    "stripping tape",
    "naillife",
    "yvynails",
    "nailtech",
    "laquenailbar",
    "nextlevelnails",
    "nailstodiefor",
    "wine",
    "deep",
    "opi polish red classics",
    "getbuffednails",
    "shoes",
    "brights",
    "fimo",
    "nemo",
    "designer",
    "paw",
    "pets",
    "paw prints",
    "under the sea",
    "marina",
    "robin moses",
    "robinmosesnailart",
    "gelaze",
    "grinch",
    "marble nail art",
    "dandelions",
    "lsu",
    "lsunails",
    "destinydayspa",
    "kandiewinchester",
    "collegeteams",
    "gotigers",
    "bright flowers french",
    "animalprint",
    "lisafrank",
    "summer nail art",
    "3dnail art",
    "food nails",
    "mockingjay",
    "mouse",
    "rabit",
    "medusa",
    "giraffe",
    "carols",
    "animal tips",
    "aztec design",
    "aztec nail",
    "pink camouflage",
    "deer nail art",
    "chanel",
    "nail tutorial",
    "spike nail art",
    "snow camo",
    "liquid sand polish",
    "peppermint",
    "turquoise and caicos",
    "borrowed and blue",
    "mod square",
    "van dgo",
    "naughty nautical",
    "borrowedandblue",
    "modsquare",
    "vandgo naughtynautical",
    "fancy",
    "ticklemyfrancey",
    "floralmani",
    "turquioseandcaicos",
    "summermani",
    "blue and silver",
    "diamanties",
    "artistic nail design",
    "citrus nails",
    "trist",
    "arte y nails club",
    "step by step",
    "uГ±as de salon",
    "bella martinelli",
    "nai art",
    "christmasnails",
    "water fall nail art",
    "orly gel fx",
    "gel mani",
    "lavendar",
    "color changing gel",
    "le chat perfect match mood ge",
    "paisley",
    "gel marbled nails",
    "black gel glitter",
    "snow globe",
    "purple stipes",
    "gel ii",
    "gel 2",
    "gel two",
    "bellamartinelli arteynailscl",
    "nailartgallery handpainted",
    "splatter nails",
    "blu",
    "water green",
    "trumpgelusa",
    "gel glitter",
    "christmas designs",
    "christmas garland",
    "snowflakes stickers",
    "emerald green",
    "opi lines",
    "chalkboard",
    "nightmare before christmas",
    "masks",
    "balls primary bright abstract",
    "waterfall",
    "stained glass nails",
    "rainbows",
    "1980s",
    "gotham city",
    "cmoic books",
    "mix",
    "my little pony",
    "love-birds",
    "fleur de lis",
    "roar",
    "fleur de lis nails",
    "eveything neon",
    "beginner",
    "diy nail art",
    "fleur",
    "zelda",
    "dentelle",
    "manucure",
    "roots",
    "alien",
    "extraterrestrial",
    "3d bow",
    "shapes",
    "nail dangle",
    "niconails",
    "livelovecarnival",
    "pointed",
    "long fingers",
    "cover pink",
    "netting",
    "christmas ornaments",
    "chapagne glasses",
    "christmas sock",
    "lettering",
    "jolly santa",
    "ugly christmas sweater",
    "spun sugar",
    "face",
    "roygbiv",
    "tears",
    "teardrops",
    "presents",
    "present",
    "challenge",
    "christmas presents",
    "frosty",
    "family",
    "family portret",
    "portret",
    "rudolph",
    "moustache",
    "blossom",
    "multichrome",
    "tweed",
    "tweed pattern",
    "rock",
    "mtv",
    "ema",
    "awards",
    "creepy",
    "cauldron",
    "eyeball",
    "creepy cauldron",
    "fishbone",
    "worm",
    "wallpaper flowers",
    "crystal",
    "soakoffgelpolish",
    "lechatperfectmatch",
    "autism awareness",
    "blue glitter nails",
    "autism",
    "paint it blue",
    "light it up blue",
    "college",
    "arizona",
    "collegiate",
    "university of arizona",
    "u of a",
    "wildcats",
    "day of the dead",
    "dia de los muertos",
    "zombies",
    "tv shows",
    "walking dead",
    "spider webs",
    "gradient toenails",
    "lacd nail art",
    "nail art desig.",
    "fench manicure",
    "el corazon base",
    "stencil",
    "world",
    "planet",
    "zodiac",
    "mauve",
    "dnd daisy",
    "fuchsia",
    "almond nail",
    "paros manicure",
    "whiteweddinggel",
    "orly freestyle",
    "esmaltedeuГ±as",
    "chromenails",
    "uГ±asdecoradas",
    "esmaltestint",
    "esmalte de uГ±as",
    "gameboy",
    "fandom",
    "outline",
    "50s",
    "fifties",
    "sprin",
    "pink and grey",
    "space invaders",
    "super mario",
    "tetris",
    "by hand",
    "story",
    "stamping and freehand",
    "video",
    "newspaper nails",
    "not a pro",
    "acylics",
    "rose glimmer",
    "oval",
    "bordeaux",
    "red wine",
    "blackfox",
    "red and yellow",
    "kitten",
    "writing",
    "blue nail polish",
    "paillettes",
    "evil queen",
    "wycon",
    "italian brands",
    "black glitter",
    "total balck",
    "so stylish",
    "milkynails",
    "head",
    "pink ribbon",
    "october",
    "marbled acrylic",
    "white and black",
    "green and blue",
    "moroccan style",
    "leaves nail art",
    "autumnal nail art",
    "maple nail art",
    "fading",
    "drips",
    "opi builder gel",
    "cnd shellac for feather",
    "square shape",
    "new trend",
    "glass effect",
    "broken mirror",
    "red black and white",
    "РїРµРґРёРєСЋСЂ РІ РјР°СЃСЃС‹",
    "toe nails",
    "badassnails",
    "summer winter",
    "french bulldog",
    "bulldog",
    "gradient. bright",
    "nail polsh",
    "chichicosmetics",
    "butterflys",
    "black and neon",
    "black and white nails",
    "nai wraps",
    "sheep",
    "sharpie mani",
    "seahorses",
    "purple and silver",
    "messy mansion",
    "green nails. bundle monster",
    "nail lacquer",
    "neon stamping",
    "zebra stamping",
    "tiger print",
    "chesire cat",
    "lion king",
    "101dalmatians",
    "disney nailart",
    "chococat",
    "sincerely polish",
    "paws",
    "fingerpaint",
    "family guy",
    "kind",
    "rocko",
    "avengers",
    "mario",
    "video games",
    "super mario brothers",
    "mario brothers",
    "rugrats",
    "chuckie finster",
    "90s cartoon",
    "baby",
    "gender reveal",
    "mac pigment",
    "captionartscreens",
    "liquid and powder",
    "american flag",
    "new years",
    "snowflake nails",
    "swirl nails",
    "fourth of july nails",
    "redwhiteblue",
    "absract",
    "winter nails. black and white",
    "pebble nail",
    "pink toes",
    "alpine snow",
    "nai",
    "3dgel",
    "gun",
    "chain",
    "xkays_creations",
    "sunshine",
    "beahc",
    "nail art desing",
    "spider web nails",
    "boo nails",
    "samantha beauty",
    "nailsticker",
    "halloweennailart",
    "catnailart",
    "cat eyes",
    "orange and yellow",
    "bat",
    "glitter mix",
    "antimony",
    "fluoro",
    "lumiere",
    "nail charms",
    "bone nails",
    "3d nail charms",
    "scream",
    "scream queens",
    "zombie",
    "elf",
    "gingerbread man",
    "candy cane nails",
    "hat",
    "googly",
    "penguins",
    "christmas sweater",
    "baubles",
    "burgandy",
    "penguin",
    "de la muerta",
    "chicks",
    "nail by william",
    "egg",
    "robin",
    "speckled",
    "robins eggs",
    "chocolate egg nails",
    "easter egg",
    "rabbits",
    "sharpie art",
    "chick",
    "rabbit foot",
    "pale",
    "pink panther",
    "polishm",
    "duck",
    "easter eggs",
    "v shaped",
    "white mani",
    "bugs bunny",
    "looney toons",
    "thanksgiving nails",
    "cotton candy nails",
    "designer nails",
    "coach nails",
    "diamond ring",
    "dailycharme",
    "acrylic mails",
    "color powdered",
    "signaturenailsystems",
    "sns powder",
    "dipping powder",
    "РїРµРґРёРєСЋСЂ",
    "retro design",
    "nagel",
    "autumn nail art",
    "cuggio colour",
    "water mable",
    "autumn colors",
    "cuccio colors",
    "seche vite",
    "monochrome nails",
    "aztec nail art",
    "water decal nail wraps",
    "swatch time",
    "butterly wings",
    "advanced stamping",
    "wayer decals",
    "lightning bolt",
    "nail vinyls nail art",
    "naitical nail art",
    "bow nail art",
    "grasient nails",
    "abstarct design",
    "cute design",
    "cute toes",
    "ellegant manicure",
    "nail decorations",
    "lavender nails",
    "black and wtie",
    "sandwich nail art",
    "aquarelle tints",
    "orly in the mix",
    "pipedreampolish",
    "dripping nail art",
    "canada",
    "maple leaf",
    "lilo and stitch",
    "jeans nails",
    "foil nail art",
    "chaveon",
    "floral nail design",
    "cool nails",
    "stsmping nail art",
    "foil effect",
    "music nail art",
    "trooical beach",
    "braid",
    "braid nail art",
    "aquerelle tints",
    "creame nail polish",
    "match",
    "mac",
    "pink color",
    "sideways",
    "strawberry",
    "neon french",
    "quilted nail design",
    "cream polishes",
    "lily",
    "neon green",
    "awesome nail art",
    "no tools needed",
    "collage",
    "converse",
    "sakura",
    "awesome nails",
    "flakies",
    "purple polish",
    "frenchmanicure",
    "notape",
    "strips",
    "taped manicure",
    "ha",
    "bubble gum pink",
    "wine red",
    "spiked punch",
    "polish love",
    "mood gel polish",
    "water fall",
    "faburnails fun-14",
    "ruffian",
    "flakes",
    "sugar shimmer",
    "white design",
    "sweden",
    "req_lucia",
    "req",
    "youngnails",
    "babyboom",
    "frenchfading",
    "blue french",
    "black and nude",
    "coverpink",
    "avon",
    "red nail",
    "shell nail",
    "la",
    "french polish",
    "bea",
    "pinkgelpolish",
    "uv lampe",
    "negle",
    "negle kursus",
    "\\ud83c\\udf38nails nailedbystacy boise",
    "cactus",
    "mexican",
    "akzentz",
    "options gel",
    "sculptured nails",
    "baby boomer nails",
    "silver glitter nails",
    "mayou london",
    "harry potter nails",
    "ldnailsxo",
    "these nails are not mine! fan",
    "paisley design",
    "snowmen",
    "light violet",
    "emerald",
    "3-d acrylic",
    "step-by-step",
    "ladynailzz",
    "wildside nai",
    "stick",
    "snakeskin",
    "groovy",
    "far out",
    "1970s",
    "nail poish",
    "christmas red glitter natale s",
    "argento",
    "natale",
    "rosso",
    "fiocco di neve",
    "classynails",
    "thermo",
    "nail art tape",
    "termic",
    "basic",
    "white flowers",
    "maroon",
    "nail tap",
    "flicks",
    "leopard nails",
    "ibd just gel",
    "black spiders",
    "v",
    "striped design",
    "neon french handdesign ",
    "le",
    "gellack",
    "news",
    "handdesign ",
    "handdesign",
    "red bottoms",
    "pointy acrylic nsils",
    "heatsensative",
    "4 in the morning",
    "push and shove",
    "kiss me or elf",
    "so elegant",
    "evileye",
    "gree",
    "thrill seeker",
    "greenfluoflowersgelnailart",
    "summergreenflowermicropaint",
    "pinkfluonailsflowers",
    "whitebabyboomermicropaintfl",
    "salon perfect",
    "nsinails attraction polishpro",
    "glue-on",
    "toxic",
    "through the looking glass",
    "rose nails",
    "nails salon",
    "esmalte para uГ±as",
    "nailart polish",
    "nailartgallery",
    "sandyfinish",
    "mattetopcoat frenchmanicure",
    "brown nails",
    "ubermat",
    "chromecolor",
    "magican assistant",
    "blue and purple",
    "messymansion",
    "sallyhansen",
    "swavarski",
    "elegant manicure nail",
    "nailfashion",
    "cutenails",
    "newnails",
    "sample nails",
    "bold",
    "overlays",
    "bb8",
    "holden",
    "chevrolet",
    "v8 supercars",
    "races",
    "emoji",
    "damask",
    "apples",
    "sci-fi",
    "umbrella",
    "multi colour",
    "rainy",
    "stamping stamping nail art",
    "panceatic",
    "sugar skulls",
    "ladies",
    "fingerprints",
    "nail art designs stamping",
    "stampin nail art",
    "silver and purple",
    "bourjois",
    "green. stamping",
    "nail jewelry",
    "hibiscus nails floral",
    "halloweenstampingplate",
    "ladyqueen.ladyqueennailart",
    "nail it",
    "nailed",
    "under the sea theme",
    "monroe",
    "pink black short square",
    "glitter black gold matt",
    "stiletto pointy blacknotsoblac",
    "leafnails",
    "anchors",
    "shirt",
    "summer mani",
    "light brown",
    "names",
    "kodi",
    "nudenails longnails ombrena",
    "eastern",
    "nailskelowna egobeauty ilov",
    "pigments.",
    "muffin",
    "ring finger",
    "full set gel nails",
    "crystalnails",
    "initial nail",
    "armynails",
    "butterfly wing",
    "glue-ons",
    "new year",
    "black lace",
    "marynailsparma",
    "sushi",
    "arrows",
    "scarf pattern nails",
    "blackvioletnailselegancenai",
    "pink & gold",
    "pink gelpolisj",
    "bluewhitemat",
    "points",
    "mylar",
    "dark pink",
    "broken glass",
    "pinks",
    "cross on chain",
    "artistic nail",
    "acrylic flowers",
    "light nail",
    "lovely nails",
    "shell nails",
    "ichthyosis",
    "bats",
    "france",
    "monochromatic",
    "hotpink",
    "overlay",
    "native american",
    "pink nail",
    "nail sweater",
    "beauty nail",
    "dashing diva",
    "ntna",
    "pink and white nails",
    "hip cop",
    "color changing",
    "gelii",
    "acryl",
    "embellishment",
    "nails by lynzee",
    "melbourne nails",
    "spirals",
    "negative space nails",
    "youtube channel",
    "blank",
    "stamping polish",
    "owl nails",
    "fashionable",
    "per design nail tips",
    "french pink",
    "mermaid effect",
    "linear",
    "champagne",
    "short stiletto",
    "slim",
    "lavand",
    "charm",
    "zigzags",
    "daily hues nail lacquer",
    "fun-14",
    "a england",
    "fancy gloss",
    "white & silver",
    "v tips",
    "frost",
    "aruba blue",
    "licorice",
    "dry stamping",
    "cinderella nails",
    "cartoon. princess",
    "scaled gradient",
    "translucent",
    "pink and sliver",
    "wraps nail",
    "plastic marbled",
    "kozmic",
    "cling wrap",
    "velvet",
    "fruit nails",
    "gelousnailsnh",
    "magpie",
    "inklondon",
    "aqua green",
    "young nails glitter",
    "nina pro",
    "aurumn nail art",
    "pastel pink",
    "clean",
    "evil queen nails",
    "structure nail",
    "structure",
    "baby bommers.",
    "pink and gold nails",
    "fashion nais",
    "mineral pigment",
    "pigments",
    "change color nail",
    "plain nail",
    "highlighter yellow",
    "kunstige negle",
    "falske negle",
    "gele nail art",
    "gelenegle",
    "gele negle design",
    "gele negle kunst",
    "bornprettystorenailart",
    "recreation",
    "aboriginal",
    "gymaroos",
    "gymnaestrada",
    "orangebluenailartвќ¤пёЏ",
    "blue & silver",
    "frenchnailartblackwhitesil",
    "darkpinknailartlongnailвќ¤пёЏ",
    "blue leopard print",
    "colour gel polish",
    "bbf stamping plates",
    "press sample",
    "iluvyournails",
    "line work",
    "colorclub",
    "splash",
    "una.",
    "dipping nails",
    "turtle shells",
    "gold feather",
    "animal planet",
    "flowetzebrastipesnailartвќ¤",
    "laces",
    "tender",
    "red and pink",
    "magnet polish",
    "atlanta braves",
    "audrey hepburn",
    "glittery",
    "good gossip",
    "fifty shades of grey",
    "grow young",
    "mix match",
    "forever nails",
    "skulls leopard",
    "guitars",
    "heart candy",
    "periodic table",
    "pokeball",
    "i choose you",
    "stilettonails",
    "green and white",
    "zodiac nails",
    "buttons",
    "greek",
    "blue.red",
    "tmnt",
    "aces",
    "captain phasma",
    "disco",
    "pink manicure",
    "nails decoration",
    "xoxo",
    "pinknailartfloweranimalprin",
    "pixar",
    "cars",
    "bluewhiteflowernailartвќ¤пёЏ",
    "alice",
    "granite",
    "venice",
    "sunrise",
    "gold charms",
    "neiru",
    "dot",
    "popular",
    "pearlescent",
    "distressed",
    "rose nail art",
    "green and pink",
    "circles and dots",
    "chaniaglaze",
    "arrow",
    "gold and blue",
    "foa",
    "australia",
    "tourist",
    "red polish",
    "black polish",
    "grey polish",
    "nail trends",
    "aztec nails",
    "creme",
    "big hero 6",
    "flinstones",
    "american apparel",
    "50 shades of grey",
    "bondage nails",
    "leather",
    "etnico hand painted",
    "pond mani",
    "pond manicure",
    "shamrocks",
    "leopardgreennailartsuperвќ¤пёЏ",
    "girl",
    "retro nails",
    "compass",
    "light elegance glitter bow gel",
    "science fiction",
    "star trek",
    "purple. bunny",
    "cover nails",
    "ncla nail wrap",
    "mix nail art",
    "madonna",
    "winter nail design",
    "unicorn nails",
    "multi",
    "stylish",
    "glamnails",
    "naillove",
    "nails max",
    "pop",
    "nude pink",
    "chevron nail art",
    "hexagon",
    "satin",
    "dry brushing",
    "semilac",
    "cosmic",
    "sea stars",
    "bayshore",
    "whale",
    "clovers",
    "oriental design",
    "peeps",
    "glamour nails",
    "guides",
    "shanail stickers",
    "ibd",
    "bird",
    "glass",
    "synergy",
    "country girl",
    "flower nails",
    "acrylic acrylicdesigns nail",
    "doctor who",
    ")",
    "leaf nails",
    "black swirl nails",
    "blackandwhite fashion stil",
    "vetro",
    "jelly",
    "starry sky",
    "gel pink nailart daisy",
    "french white",
    "white and blue",
    "nailcharms",
    "4dbow",
    "softwhite",
    "multi color",
    "mia secret",
    "chrome mirror",
    "cooi",
    "alice in wonderland nails",
    "ellen degeneres",
    "pastel galaxy",
    "drymarble",
    "elegantnailsbyrose disneyart",
    "wrap",
    "transfers",
    "stamp[",
    "two fingers different",
    "blue beige",
    "srca",
    "prima kozmetika",
    "movie inspired",
    "drymarbling",
    "tokyo",
    "zoya kendal",
    "sweetheart",
    "wizard",
    "painting",
    "polish pen",
    "image plate",
    "couple",
    "multi coloured",
    "cover",
    "cherries",
    "turkey",
    "st. patricks day nails",
    "zircons",
    "mummy",
    "deborah lippmann",
    "ciate",
    "water colors",
    "side french",
    "zebra print",
    "fabric",
    "maybelline",
    "scales",
    "mood change",
    "pinterest",
    "flamingos",
    "lights",
    "stained glass",
    "simple nail art",
    "boho",
    "nailgasm",
    "santa nails",
    "textured polish",
    "gold nails",
    "alcohol ink",
    "trendy freehand",
    "sweater nails",
    "fireworks",
    "kbshimmer",
    "science",
    "paint",
    "opi sheer tints",
    "tropical flowers",
    "geometric nails",
    "zigzag",
    "floral design",
    "hogwarts",
    "i-scream-nails",
    "shabby",
    "festival",
    "2015",
    "net",
    "3d roses",
    "glacier nail",
    "led gel",
    "china cheap uv gel polish",
    "sunflowers",
    "pineapple",
    "newspaper",
    "spooky",
    "wavy stripes",
    "yellow and black",
    "pipe",
    "denim",
    "jeans",
    "gel nail art",
    "cnd shellac",
    "fall leaves",
    "glitter nail art",
    "anchor nails",
    "marvel",
    "pois",
    "zuzanna nails",
    "tiffany blue nails",
    "3dnails",
    "lovely",
    "swan tutorial",
    "carnival",
    "crackle polish",
    "wild",
    "nailswag",
    "wave",
    "akryl negle",
    "negletipper",
    "neglelim",
    "football",
    "kpop nail art",
    "floral nails",
    "sheer nails",
    "periwinkle",
    "black cherry",
    "dreamcatcher",
    "sparkling",
    "olaf",
    "food nail art",
    "nail perfect",
    "liquid stone",
    "jewellery nail art",
    "bones",
    "fish bones",
    "sun",
    "sea horse",
    "star fish",
    "beach themed",
    "christmas lights",
    "beach nails",
    "blue and pink",
    "neon nail art",
    "3d acrylic nails",
    "minnie mouse nails",
    "kawii",
    "kawii nails",
    "cartoon nails",
    "acrylic nail art",
    "pinky",
    "toad",
    "yoshi",
    "mario and luigi",
    "mario bros",
    "words",
    "pastel colors",
    "ice nails",
    "fish tail",
    "вќ¤пёЏ",
    "cross",
    "black and pink",
    "sharks",
    "pink and white",
    "santa claus",
    "mardi gras",
    "funky",
    "hunger games",
    "bear",
    "elephant",
    "zoo",
    "wildlife",
    "rudolph the red nosed reindee",
    "grey nails",
    "3d rose",
    "spike nails",
    "independence day",
    "accent",
    "dotting tools",
    "christmas nail art",
    "mask",
    "rainbow theme",
    "rainbow nail art",
    "80s",
    "batman",
    "little mermaid",
    "tiger stripes",
    "camoflauge",
    "vegas",
    "arabesque",
    "glass nails",
    "merry christmas",
    "glass fleck",
    "smile",
    "blue and gold",
    "movember",
    "scary",
    "witch",
    "nailstamping",
    "glacier",
    "metal studs",
    "spiders",
    "water spotting",
    "jewelery",
    "dark red",
    "madam glam",
    "chromemirror",
    "lovenails",
    "8 bit",
    "pixelated",
    "arcade",
    "double stamping",
    "first time",
    "purple and black",
    "lace nail",
    "soft",
    "pupa",
    "rebel temptation",
    "glass nail",
    "colorful french",
    "shattered glass",
    "decal",
    "forest",
    "winstonia",
    "safari",
    "awareness",
    "dogs",
    "disneyland",
    "sanrio",
    "long",
    "funny",
    "naildork",
    "nickelodeon",
    "90s",
    "geek",
    "nerd",
    "sns",
    "sequins",
    "blue and red",
    "lancengi",
    "argyle",
    "not polish",
    "holly",
    "holiday nails",
    "micro beads",
    "presto",
    "encapsulated nails",
    "unhas",
    "reverse french",
    "nai art design",
    "cirque colors",
    "tape manicure",
    "morgan taylor",
    "jeans nail art",
    "modern french",
    "dream catcher",
    "reciprocal gradient",
    "water decal",
    "milvru",
    "eiffel tower",
    "poker",
    "pastel neon",
    "pedi time",
    "moon",
    "tattoo",
    "stone",
    "caviar nails",
    "matt",
    "skull",
    "moyoulondon",
    "diamante",
    "nailsbylinda",
    "loreal",
    "nails airbrush handdesign ",
    "rose red nail",
    "fullset",
    "nail4you",
    "vegan nails",
    "harry potter",
    "picture polish",
    "ombre nails",
    "free hand",
    "brillantini",
    "sfumatura",
    "coffin shape",
    "gothic",
    "pronails",
    "rockstar",
    "queen of hearts",
    "nailsbymegen",
    "uГ±as decoradas",
    "chinaglaze",
    "radial gradient",
    "prettynails",
    "nailtrend",
    "swarvoski",
    "stamping plates",
    "hard candy",
    "swirly",
    "models own",
    "sinful",
    "rose gold",
    "neon yellow",
    "elegant nails",
    "lady queen",
    "barrym",
    "plover",
    "nail decals",
    "glamour",
    "stamps",
    "japanese",
    "lol",
    "spotty nails",
    "knitted",
    "dark purple",
    "raspberry",
    "smile lines",
    "indie nail polish",
    "fairy dust",
    "color block",
    "banana",
    "baby pink",
    "nails nailart naildesign a",
    "pikachu",
    "addictive",
    "stud",
    "miracle gel",
    "water spotted",
    "atlanta",
    "zoella",
    "negativespace",
    "striping",
    "twinkledt",
    "sky",
    "color outbreak",
    "office appropriate",
    "futbol",
    "fishnet",
    "watercolor",
    "firtree",
    "lemon",
    "thenailprince",
    "pantone",
    "flower glitter",
    "food",
    "elegantnailsbyrose tammytayl",
    "pentagram",
    "pavilion",
    "royal blue",
    "stamping design",
    "tweed nails",
    "awesome",
    "round gradient",
    "teddy bear",
    "halloween nail art",
    "graffiti",
    "thermal",
    "japanese nails",
    "halloween 2015",
    "lechat",
    "autumn nails",
    "lcn",
    "artnails",
    "topnails",
    "beuty",
    "nice",
    "glitter ombre",
    "books",
    "artificial nails",
    "patchwork",
    "blood",
    "queen",
    "drawing",
    "summernails",
    "beads",
    "uv gel",
    "nautical nails",
    "nails done right",
    "modern",
    "animal print nails",
    "art deco",
    "studded nails",
    "golden",
    "gold studs",
    "sheer",
    "leadlight",
    "egyptian",
    "party nails",
    "birthday",
    "cupcake nails",
    "barbie",
    "purple and white",
    "foil gel",
    "born pretty store",
    "short",
    "white tips",
    "white nails",
    "cookie monster",
    "sesame street",
    "dope",
    "mix media",
    "french acrylic",
    "candy corn",
    "diamond",
    "indie",
    "nintendo",
    "galaxy nail art",
    "camouflage",
    "kiwi",
    "gellyfit",
    "nails magazine",
    "finding nemo",
    "daisy",
    "fire",
    "peacock",
    "dott",
    "artistic colour gloss",
    "masquerade",
    "princess",
    "coffinnails",
    "top coat",
    "bone",
    "gemstones",
    "elcorazon",
    "miasecret",
    "miasecretvzla",
    "bride",
    "apple",
    "nailcharmid",
    "pedi",
    "nature",
    "bees",
    "extension",
    "apricot",
    "trumpgel usa",
    "memorial day",
    "antondesigns",
    "red glitter",
    "tattoos",
    "sns nails",
    "disney nails",
    "slider design",
    "sheer tints",
    "cut out",
    "berry",
    "green and black",
    "creative",
    "duochrome",
    "leaf",
    "zig zag",
    "strass",
    "navy blue",
    "wet n wild",
    "glitternails",
    "scifi",
    "sliver",
    "mixed",
    "finger paints",
    "julep",
    "kiss",
    "maniq",
    "colorful nail art",
    "crazy",
    "false nails",
    "iridescent",
    "cinderella",
    "nail vinyl",
    "glitter placement",
    "pokemon",
    "mlb",
    "sequin",
    "i scream nails",
    "dappled",
    "mundo de unas",
    "gelpaint",
    "mundodeunas",
    "eye",
    "spider",
    "spider web",
    "kaleidoscope nail polish",
    "delicate",
    "usa",
    "bohemian",
    "howto",
    "gelcolor",
    "santa",
    "one step gel",
    "sharpie",
    "chrome nails",
    "yellow nails",
    "nail charm",
    "black and red",
    "unicorn",
    "sculptured acrylic nails",
    "pure ice",
    "magenta",
    "nails by linda",
    "silver nails",
    "nail tape",
    "shells",
    "chocolate",
    "audrey destefano",
    "leneha junsu",
    "baseball",
    "sponging",
    "cupcake",
    "dorota palicka",
    "transfer foil",
    "texture",
    "sand",
    "starfish",
    "hibiscus",
    "flag",
    "cookies",
    "camo nail art",
    "movies",
    "reindeer",
    "camo nails",
    "letter",
    "sponge",
    "bronze",
    "triangle",
    "sugar spun",
    "holographic polish",
    "camo",
    "spikes",
    "snowman",
    "taupe",
    "holidays",
    "pedi time with yagala",
    "https://www.facebook.com/pages",
    "green nails",
    "game",
    "abstact",
    "chevron nails",
    "cream",
    "sephora",
    "gel effect",
    "mirror",
    "black and silver",
    "aqua",
    "moyou london",
    "longnails",
    "lace nails",
    "РЅРѕРіС‚Рё",
    "black and gold",
    "girly nails",
    "skittlette",
    "stone marble",
    "macro",
    "paris",
    "valentines",
    "picturepolish",
    "sugaring",
    "watermarble",
    "crown",
    "nailsbycarla",
    "el corazon nail polish",
    "stainless",
    "steel",
    "color change",
    "solar",
    "funky fingers",
    "confetti",
    "hologram",
    "color blocking",
    "tints",
    "moyou",
    "inspired",
    "water marbling",
    "konad stamp",
    "print",
    "colourful",
    "lisionok2004",
    "airbrush",
    "easter nails",
    "barbie pink",
    "white french",
    "hot",
    "toenail art",
    "bopp",
    "ribbon",
    "comics",
    "chic",
    "seashells",
    "purenails",
    "bornpretty",
    "seashell",
    "lime green",
    "pumpkin",
    "barbie nails",
    "glow in the dark",
    "stamping plate",
    "rockstar nails",
    "minx",
    "tan",
    "sea shells",
    "hello kitty nail design",
    "pearl",
    "lips",
    "ornaments",
    "daisies",
    "yeg",
    "studded nail art",
    "color",
    "sports",
    "skulls",
    "star wars",
    "cuccio veneer",
    "gray",
    "fullcover",
    "kawaii",
    "black and yellow",
    "polkadots",
    "america",
    "jamberry",
    "coffee",
    "tie dye",
    "light pink",
    "fashion nails",
    "earthynails",
    "popular nails",
    "neons",
    "margaritasnailz",
    "transfer",
    "uber chic",
    "efexclusive",
    "paznokcie",
    "РЅРѕРєС‚РёС‚Рµ",
    "elegantnailsbyrose",
    "polka dot",
    "copper",
    "bows",
    "ncla",
    "rabbit",
    "birds",
    "tape mani",
    "nokti",
    "dry brush",
    "prom",
    "gele negle",
    "madjennsy",
    "light blue",
    "pointy nails",
    "purjoi nail studio",
    "bunny",
    "music",
    "sweater",
    "claws",
    "shell",
    "ice",
    "glitters",
    "aztec",
    "nail salon in oviedo fl",
    "spots",
    "japanese nail art",
    "frozen",
    "romantic",
    "barry m",
    "minions",
    "bridal nails",
    "sculpted acrylic",
    "pointy",
    "easter bunny",
    "sinful colors",
    "natural nail designs",
    "swirl",
    "РјР°РЅРёРєСЋСЂ",
    "butterfly nails",
    "mdu",
    "water",
    "wildflowersacademy.com",
    "plates",
    "ranails",
    "eurofashion",
    "cherry",
    "hard gel",
    "nailtalk",
    "palm trees",
    "dotting tool",
    "matte nails",
    "animal",
    "sculpted",
    "nail sticker",
    "color club",
    "vinyls",
    "essence",
    "tree",
    "sponged technique",
    "ghost",
    "chains",
    "anchor",
    "metal",
    "owls",
    "cherry blossom",
    "hawaii",
    "breast cancer awareness",
    "purple nails",
    "black french tip",
    "minnie mouse",
    "mickey mouse",
    "acrylic glitter",
    "pink and blue",
    "splatter",
    "animal nail art",
    "aquarium",
    "holographic glitter",
    "milv",
    "dark",
    "gamer",
    "tv",
    "kiko",
    "watermelon",
    "lady queen nails",
    "esmaltes da kelly",
    "thanksgiving",
    "sweet",
    "sexy",
    "snake skin",
    "marbling",
    "saran wrap",
    "monochrome",
    "lavender",
    "waves",
    "jewels",
    "pueen",
    "pink glitter",
    "baby blue",
    "butterflies",
    "clear",
    "rainbow nails",
    "colored acrylic",
    "acrylic designs",
    "lady queen nail",
    "cupcakes",
    "alice in wonderland",
    "french manicure with colour",
    "acrylc",
    "cats",
    "stones",
    "shimmer",
    "rhinestone nail art",
    "bundle monster",
    "wedding",
    "faburnails",
    "candy",
    "pink and purple",
    "designs",
    "nailstyle",
    "nails desing",
    "nailswang",
    "nails polish",
    "plate",
    "beige",
    "bioseaweed gel",
    "bioseaweedgel",
    "gems",
    "red and gold",
    "red nails",
    "3d flowers",
    "multicolor",
    "nailpolish",
    "revlon",
    "star",
    "hello kitty",
    "feather",
    "konad",
    "space",
    "dry marble",
    "classic",
    "fish",
    "colorful nails",
    "tribal print",
    "neon nails",
    "uberchicbeauty",
    "gels",
    "pattern",
    "hot pink",
    "mix and match",
    "french twist",
    "encapsulated",
    "yellow nail art",
    "cheetah",
    "cool",
    "festive",
    "cat",
    "chrome",
    "navy",
    "abstract nails",
    "ice cream",
    "movie",
    "abstract nail art",
    "rose",
    "morgantaylor",
    "template",
    "candy cane",
    "bio seaweed gel",
    "tribal nails",
    "nailsofpromise",
    "acrylic and hand painted",
    "pearls",
    "purple glitter",
    "eyes",
    "burgundy",
    "mint",
    "indie polish",
    "tape",
    "reverse stamping",
    "one stroke flower nail art",
    "swirls",
    "galaxy nails",
    "leaves",
    "lines",
    "sculpted gels",
    "sticker",
    "natural",
    "3d acrylic flowers",
    "galaxy",
    "mermaid",
    "diy",
    "nailartwow",
    "nailartoohlala",
    "nails2inspire",
    "internnails",
    "uГ±asbellas",
    "sunset",
    "neutral",
    "dotticure",
    "nail vinyls",
    "youtube",
    "fruit",
    "snowflake",
    "feet",
    "neon pink",
    "glitter polish",
    "cartoon",
    "tips",
    "tiger",
    "feathers",
    "bright colors",
    "easy",
    "lilac",
    "red and white",
    "real nails",
    "pastel nail art",
    "snow",
    "uberchic",
    "square",
    "pastels",
    "3d bows",
    "fall nails",
    "disney nail art",
    "glitter french",
    "classy",
    "shiny",
    "geeky",
    "nailartaddict",
    "plaid",
    "pink nail art",
    "cheetah print",
    "violet",
    "nautical",
    "3d flower",
    "nageldesign bilder",
    "teal",
    "nerdy",
    "naildesigns",
    "naturalnails",
    "swatch",
    "geometric",
    "zoya",
    "pretty",
    "bright",
    "gel nail",
    "diamonds",
    "3d nails",
    "cnd",
    "red white and blue",
    "vintage",
    "half moon",
    "fade",
    "sea",
    "sally hansen",
    "coral",
    "axxium",
    "sparkles",
    "wedding nails",
    "charms",
    "metallic",
    "halloween nails",
    "sparkly",
    "murals",
    "decals",
    "artnail",
    "mani",
    "holo",
    "tribal",
    "decoration",
    "retro",
    "3d acrylic",
    "butterfly",
    "aliki chatzipanagiotou nails",
    "cartoon characters",
    "autumn",
    "palm tree",
    "red and black",
    "french tips",
    "rhinestone",
    "acrylics",
    "\\ud83d\\udc85\\ud83c\\udffb\\ud83d\\udc95\\ud83d\\udc95nails nailart handp",
    "з€Є",
    "uГ±as",
    "https://vk.com/cherry_nail_stu",
    "tammytaylor.com",
    "alice through the looking gla",
    "alysnails",
    "arcanelacqer",
    "artscreens",
    "bee mani",
    "best nail salons in dubai",
    "cake pop cream puff and black",
    "china glaze.blue",
    "chique nails",
    "coloroutbreak",
    "diner",
    "elegantnailsbyrose ballerina",
    "elegantnailsbyrose exclusive",
    "ellen show",
    "finger",
    "fishtail braid",
    "french mani",
    "gel polosh",
    "gliiter nails",
    "great",
    "hippocampus",
    "inspire",
    "inspired by pinterest",
    "instagram - cherry_nail_stud",
    "kb shimmer sarong place sarong",
    "kc royals",
    "klingon",
    "knuckle",
    "la colors",
    "lak za nokte",
    "lava lamp",
    "letter featherпјЊ nail art пјЊstam",
    "love birds",
    "love letter",
    "lovers",
    "lucifer",
    "lunar new year",
    "lv",
    "maniswap",
    "mia secret venezuela",
    "misuГ±as",
    "mls",
    "mongolian pattern gumiho yuki",
    "mood polish",
    "mood acrylic",
    "muddy girl",
    "mynails",
    "nail art in dubai",
    "nail salon dubai",
    "nailartnailsgelblue",
    "nails by lexi",
    "nails fashion",
    "nailsbycatie",
    "nailsntnatop24",
    "nailsoftheday ombrenails o",
    "negativespace neon",
    "nude polish",
    "nyc",
    "paste",
    "patriotic",
    "pettern",
    "pink nails. caviar beads",
    "pink valentine heart xox ",
    "prirodni nokti",
    "satanism",
    "seasonal",
    "sheer tint",
    "shibuya",
    "striking",
    "tip top",
    "tips stickers",
    "tool",
    "with encapsulated glitter and",
    "youtuber",
    "yummy",
    "zoe sugg",
    "zoella beauty",
    "nails",
    "nail art designs",
    "manicure",
    "design",
    "nail",
    "light elegance",
    "tutorial"
);
$connection = pg_connect("host=195.88.209.17 port=5432 dbname=makeup user=postgres password=12345_Vet");
$result = pg_query($connection, "SELECT tags,id FROM manicure WHERE tags NOT LIKE ''");
while ($row = pg_fetch_row($result)) {
    $ru = "";
    $tempArrayEn = explode(",", $row[0]);

    for ($i = 0; $i < count($tempArrayEn); $i++) {
        for ($j = 0; $j < count($deleting); $j++) {
            if (strpos($tempArrayEn[$i], $deleting[$j])) {
                $tempArrayEn[$i] = "";
                //$tempArrayEn[$i] = $rus[$j];
            }
        }
        for ($j = 0; $j < count($eng); $j++) {
            if (strpos($tempArrayEn[$i], $eng[$j])) {
                $tempArrayEn[$i] = "";
                $tempArrayEn[$i] = $rus[$j];
            }
        }
        while(strpos($ru, ",,")){
            $ru = str_replace(",,", ",", $ru);
        }
        $ru = $ru . $tempArrayEn[$i] . ",";
    }

    $query = pg_query($connection, "UPDATE manicure SET tags_ru='$ru' WHERE id='$row[1]'");
    if ($query) {
        print "+++++++++++++++<br>";
        print $row[0] . "<br>";
        print $ru . "<br>";
        $ru = "";
    }
}
?>
</body>
</html>